### ISSUE TITLE
Possible bug editing a client

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#107]
Stephanie Olsen's Client "Brenda	Cikkedge." Her actual last name is Cilledge. Stephanie tried updated this client’s info but it din’t work. Updating did work for her other clients.

**Comment by kuanb** [comment]
Strange, it only did not work for that one client?
I will follow up with her with an email. I wonder if it was a fluke and if she tried again if it would work? For example, could have been user error on her end of not clicking right button, etc. I think this first because it worked for all other clients.

**Comment by bpdesigns** [comment]
I would not be surprised if this was a user error. Just logged it in case we hear it from someone else

**Comment by kuanb** [comment]
I looked and it appears that she was able to edit the account information... Going to go ahead and close this.
