### ISSUE TITLE
Color group card - design

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/clientcomm#111]
original design:
![699568e8-4f4b-11e6-9b1e-3011fb05b2d0](https://cloud.githubusercontent.com/assets/15329140/17126569/afdbcfcc-52bb-11e6-98fd-5ab8e3d64e8f.png)

layout: 
- I'd like to make a space between the gray selector and the the three colors and mark it as "default"
- can you make the buttons slimmer to match the vertical pill shape?

text color: can you make the client's name white so it stands out against the color bar?

**Comment by kuanb** [comment]
i think its a trick of the eyes because of the amount of top and bottom padding you have on the color selctor card in yours, both have the same dimensions

![image](https://cloud.githubusercontent.com/assets/6053396/17158769/7a00352c-534d-11e6-8771-dd6657cfcf3e.png)


![image](https://cloud.githubusercontent.com/assets/6053396/17158774/7ee60972-534d-11e6-94ee-d573fb137964.png)


I'll make the color tags taller to exagerate to achieve similar effect

e.g.

![image](https://cloud.githubusercontent.com/assets/6053396/17158854/f3ea83ba-534d-11e6-9ced-3a570f89162f.png)


will add text

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/17158951/9c597f9c-534e-11e6-8b10-478afc067f24.png)


white text

**Comment by kuanb** [comment]
4f6971d..c844af9 resolves
